# needed modules:
server.modules += (
    "mod_webdav",
    "mod_proxy",
    "mod_setenv",
)

#setenv.add-response-header = (
#    "Access-Control-Allow-Origin" => "*",
#    "Access-Control-Allow-Headers" => "accept, origin, x-requested-with, content-type, x-transmission-session-id, x-ida-auth-token, content-disposition",
#    "Access-Control-Expose-Headers" => "X-Transmission-Session-Id",
#    "Access-Control-Allow-Methods" => "GET, POST, OPTIONS, PUT"
#    )

# for VLC -----------------------------------
# username:password for basic authentification is ':1234'
$HTTP["url"] =~ "^/requests/.*$" {
	setenv.add-request-header = (
		"Authorization" => "Basic OjEyMzQ=",
	)
#	setenv.add-response-header = (
#		"Access-Control-Allow-Origin" => "*"
#		#"Access-Control-Allow-Origin" => "http://localhost"
#        )
    proxy.server = ("" => ("" => ("host" => "localhost", "port" => 8081)))
}

# for WebDAV  without authentification --------------------------------------------------
# needs: ./configure --with-webdav-props --with-webdav-locks
# get a file with curl -v  http://localhost:8081/files/hallo.txt
# store file with curl -v -T /tmp/hallo.txt http://localhost:8081/files/hallo2.txt 

$HTTP["url"] =^ "/files/" {
    alias.url = ("/files" => "/var/www/html/files")
    dir-listing.activate = "enable" 
    webdav.activate = "enable" 
    #webdav.is-readonly = "disable" # (default)
    webdav.sqlite-db-name = "/var/www/html/db/webdav.sqlite"
} else $HTTP["url"] == "/files" {
    url.redirect = ("" => "/files/")
    url.redirect-code = 308
}

